# Generated by Django 3.1.2 on 2022-01-27 05:38

import Spaces.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=150)),
                ('comp_type', models.CharField(max_length=150)),
                ('noOfRoomsPerBath', models.IntegerField()),
                ('noOfRoomsPerToilet', models.IntegerField()),
                ('areaLocated', models.CharField(max_length=500)),
                ('timeOfTreckToGate', models.IntegerField(default=323)),
                ('powerSupply', models.BooleanField()),
                ('generator', models.BooleanField()),
                ('garage', models.BooleanField()),
                ('washingMachine', models.BooleanField()),
                ('swimmingPool', models.BooleanField()),
                ('borehole', models.BooleanField()),
                ('wellWater', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('animals', models.BooleanField()),
                ('children', models.BooleanField()),
                ('partying', models.BooleanField()),
                ('check_in', models.TimeField(null=True)),
                ('check_out', models.TimeField(null=True)),
                ('extraRules', models.TextField(max_length=1000, null=True)),
                ('ownerType', models.CharField(max_length=150)),
                ('agentComment', models.CharField(max_length=1000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=4, default=3233.434, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=4, default=32423.343, max_digits=8)),
                ('distanceToSchoolGate', models.DecimalField(decimal_places=1, default=3233.4, max_digits=6)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(max_length=50)),
                ('noOfTenantPermitted', models.IntegerField(null=True)),
                ('noOfWindows', models.IntegerField()),
                ('roomArea', models.DecimalField(decimal_places=3, default=500, max_digits=5)),
                ('roomAreaUnit', models.CharField(max_length=50)),
                ('airCondition', models.BooleanField()),
                ('kitchen', models.BooleanField()),
                ('flatscreenTV', models.BooleanField()),
                ('room_yearlyPrice', models.DecimalField(decimal_places=3, default=500, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=3, default=500, max_digits=10)),
                ('inspection_price', models.DecimalField(decimal_places=3, default=500, max_digits=10)),
                ('wardrobe', models.BooleanField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('cleaner', models.BooleanField(default=False)),
                ('bathtube', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(default='room/default.jpg', upload_to=Spaces.models.uploadroom_to, verbose_name='Image')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spaces.room')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spaces.room')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_image', models.ImageField(default='compound/default.jpg', upload_to=Spaces.models.upload_to, verbose_name='Image')),
                ('compoundId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spaces.compound')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spaces.room')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
