# Generated by Django 3.1.2 on 2022-01-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0.1, max_digits=8),
        ),
        migrations.AddField(
            model_name='compound',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='compound',
            name='comp_type',
            field=models.CharField(max_length=150),
        ),
    ]
