# Generated by Django 3.1.2 on 2022-01-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compound',
            unique_together={('comp_name', 'id')},
        ),
    ]
