# Generated by Django 4.0.2 on 2022-02-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0002_auto_20220201_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='compoundId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Spaces.compound'),
        ),
    ]
