# Generated by Django 3.1.2 on 2022-01-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0002_auto_20220112_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
        migrations.AlterField(
            model_name='compound',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
    ]
