# Generated by Django 4.0.2 on 2022-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0003_alter_room_compoundid'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
