# Generated by Django 3.1.2 on 2022-01-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0003_auto_20220127_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
