# Generated by Django 3.1.2 on 2022-01-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0004_auto_20220113_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimages',
            name='compoundId',
        ),
        migrations.AddField(
            model_name='roomimages',
            name='roomId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Spaces.room'),
        ),
    ]
