# Generated by Django 3.1.2 on 2022-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0004_auto_20220127_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='inspection_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_yearlyPrice',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
