# Generated by Django 4.0.2 on 2022-02-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0004_compound_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='taken',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
