# Generated by Django 3.1.2 on 2022-01-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0005_auto_20220127_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='compoundId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Spaces.compound'),
        ),
    ]
