# Generated by Django 3.1.2 on 2022-01-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0005_auto_20220113_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesTb',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='mapCoordinate',
        ),
    ]
