# Generated by Django 3.1.2 on 2022-01-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0006_auto_20220113_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundimages',
            name='compoundId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Spaces.compound'),
        ),
    ]
