# Generated by Django 3.1.2 on 2022-01-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0006_auto_20220127_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomArea',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
