# Generated by Django 3.1.2 on 2022-01-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0007_auto_20220114_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundimages',
            name='compoundId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Spaces.compound'),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='roomId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Spaces.room'),
        ),
    ]
