# Generated by Django 3.1.2 on 2022-01-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0009_auto_20220116_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='noOfTenantsPerBath',
            new_name='noOfRoomsPerBath',
        ),
        migrations.RenameField(
            model_name='compound',
            old_name='noOfTenantsPerToilet',
            new_name='noOfRoomsPerToilet',
        ),
    ]
