# Generated by Django 3.1.2 on 2022-01-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0010_auto_20220116_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomAreaUnit',
            field=models.CharField(default='th', max_length=50),
        ),
    ]
