# Generated by Django 3.1.2 on 2022-01-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spaces', '0011_room_roomareaunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomAreaUnit',
            field=models.CharField(max_length=50),
        ),
    ]
