# Generated by Django 3.1.2 on 2022-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
    ]
