# Generated by Django 3.1.2 on 2022-01-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset', models.IntegerField(blank=True, max_length=5, null=True)),
                ('confirm', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
