# Generated by Django 3.1.2 on 2022-01-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_myuser_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
