# Generated by Django 3.1.2 on 2022-01-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='confirm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='reset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
