# Generated by Django 3.1.2 on 2022-01-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_verificationcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verificationcode',
            unique_together={('userId', 'codeType')},
        ),
    ]
